# this file is just a stub with the signatures of the generated python bindings
# it is used by type checkers in order to provide better python hints

type JsonValue = (
    dict[str, JsonValue] | list[JsonValue] | str | int | float | bool | None
)

def benchmark_performance(json_str: str, iterations: int = 10_000) -> tuple[float, float, float]: ...
def dumps(input: JsonValue, indent: int | None = None) -> str: ...
def parse_json(input: str) -> JsonValue: ...
def parse_json_file(input_path: str) -> JsonValue: ...
