name: Continuous Integration

on:
  push:
    branches: 
      - main
      
  pull_request:

env:
  CARGO_TERM_COLOR: "always"
  UV_WORKING_DIRECTORY: "rust-json-parser"

jobs:
  run_ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: "Format Rust code"
        run: cargo fmt --manifest-path rust-json-parser/Cargo.toml --check

      - name: "Lint Rust code"
        run: cargo clippy --manifest-path rust-json-parser/Cargo.toml -- --deny warnings

      - name: "Build Rust lib"
        run: cargo build --manifest-path rust-json-parser/Cargo.toml --verbose

      - name: "Run Rust tests"
        run: cargo test --manifest-path rust-json-parser/Cargo.toml --verbose

      - name: "Set up uv"
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          working-directory: "${{ env.UV_WORKING_DIRECTORY }}"

      - name: "Set up Python"
        uses: actions/setup-python@v7
        with:
          python-version-file: "rust-json-parser/pyproject.toml"

      - name: "Install Python code with dev dependencies"
        run: uv sync --frozen --group dev

      - name: "Run ruff linter"
        run: uv run ruff check

      - name: "Run ruff formatter"
        run: uv run ruff format --check

      - name: "Run Python tests"
        run: uv run pytest

      - name: "Run benchmarks (100 iterations)"
        run: |
            uv run --no-editable --reinstall-package rust_json_parser \
              rust-json-parser benchmark \
              test_data/benchmark-small.json \
              test_data/benchmark-medium.json \
              test_data/benchmark-large.json \
              --num-iterations 100
